update `s#L_ORDERKEY from `lineitem
update `s#O_ORDERKEY from `orders
update `u#O_ORDERKEY from `orders
update `s#P_PARTKEY from `part
update `u#P_PARTKEY from `part
update `s#C_CUSTKEY from `customer
update `u#C_CUSTKEY from `customer
update `s#S_SUPPKEY from `supplier
update `u#S_SUPPKEY from `supplier
update `s#R_REGIONKEY from `region
update `u#R_REGIONKEY from `region
update `s#N_NATIONKEY from `nation
update `u#N_NATIONKEY from `nation
